version: '3.8'

services:
  nginx:
    build: .
    ports:
      - '8000:80'
      - '8100:8000'
      - '8090:8090'
    links:
      - web
      - blue
      - green

  web:
    image: nginx:latest
    ports:
      - '3000:80'

  blue:
    image: nginx:latest
    ports:
      - '10000:80'

  green:
    image: nginx:latest
    ports:
      - '20000:80'
